# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testsPoc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testsPoc
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  target 'testsPocTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testsPoc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testsPoc-tvOS

  target 'testsPoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
